apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-python-klcvjlso
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/backend-tests-python-klcvjlso:073d5f9952425ae2e9caa72cc9ae6ce7ee1d9b65@sha256:bcbf9798c9dc2c344c15d1f3ff0000c551e209e532d5c92dd98c3998fb8c479b
          name: container-image
